"""Market Risk AI Assistant V12: validated risk-run lineage."""

from archive.versions import market_risk_agent_v11 as v11
from google.genai import types

from archive.versions.market_risk_ingestion_v12 import ingest_and_validate_risk_run


VERSION = "V12"
v9 = v11.v9
v8 = v11.v8


def get_risk_run_lineage():
    """Return validation status and data lineage for the current demo risk run."""
    result = ingest_and_validate_risk_run(v8.FILE_NAME)
    return {
        "validation_status": result["validation_status"],
        "lineage": result["lineage"],
        "errors": result["errors"],
        "warnings": result["warnings"],
    }


# Register exactly one V12 agent-visible deterministic function.
v8.TOOL_FUNCTIONS["get_risk_run_lineage"] = get_risk_run_lineage
v8.TOOL_DESCRIPTIONS["get_risk_run_lineage"] = (
    "Validation status and lineage of the current demo risk-engine run, including "
    "its generated demo run ID, source file, data fingerprint, dates and scope."
)
v9.VERSION = VERSION
v9.SYSTEM_INSTRUCTION += """

V12 data-lineage control:
- get_risk_run_lineage is the source for run status and lineage facts.
- The run ID is generated by the demo adapter when the source file supplies no run ID.
- VALIDATED means the demo schema checks passed; it is not a business approval.
"""
v9.tools = [
    types.Tool(
        function_declarations=[
            types.FunctionDeclaration(name=name, description=description)
            for name, description in v8.TOOL_DESCRIPTIONS.items()
        ]
    )
]

ask_risk_agent = v9.ask_risk_agent


def main():
    print("\nMARKET RISK AI ASSISTANT — V12")
    print("Validated demo risk-run lineage is ready.")
    print("Type 'exit' to stop.\n")
    while True:
        question = input("You: ")
        if question.lower().strip() == "exit":
            print("Assistant: Goodbye.")
            break
        try:
            print("Assistant:")
            print(ask_risk_agent(question))
            print()
        except Exception as error:
            print(f"\nERROR:\n{error}\n")


if __name__ == "__main__":
    main()
