"""Market Risk AI V13: focused risk-manager pages and stress evolution."""

import pandas as pd
import streamlit as st

st.set_page_config(page_title="Market Risk AI | V13", page_icon=":material/monitoring:", layout="wide")

try:
    import market_risk_agent_v13 as v13
except Exception as error:
    st.error(f"The risk dashboard could not load its data or configuration: {error}")
    st.stop()


v12 = v13.v12
v11 = v13.v11
v8 = v13.v8

if "risk_agent_messages" not in st.session_state:
    st.session_state.risk_agent_messages = []


def amount(value):
    """Format amounts with dot thousand separators for the dashboard."""
    return f"{value:,.0f}".replace(",", ".")


def percentage(value):
    return f"{value:.1f}%"


def display_amount_table(frame, amount_columns):
    formatted = frame.copy()
    for column in amount_columns:
        if column in formatted:
            formatted[column] = formatted[column].map(amount)
    st.dataframe(formatted, hide_index=True)


def alert_badge(severity):
    return {
        "CRITICAL": ":red-badge[Critical]",
        "HIGH": ":orange-badge[High]",
        "MEDIUM": ":yellow-badge[Monitor]",
        "INFO": ":blue-badge[Information]",
    }[severity]


df = v8.df.copy()
current_risk = v8.get_current_risk()
trend = v8.get_var_trend()
limit = v8.get_limit_analysis()
backtesting = v8.get_backtesting_analysis()
alert_summary = v11.get_risk_alerts()
risk_run = v12.get_risk_run_lineage()
lineage = risk_run["lineage"]
stress_evolution = v13.get_stress_evolution()
stress_frame, stress_metadata = v13.build_stress_evolution_frame()

with st.sidebar:
    st.title("Market Risk AI")
    st.caption("Risk-manager cockpit · V13")
    page = st.radio(
        "Navigate",
        ["Overview", "VaR", "P&L", "Stress", "Controls & risk run", "Alerts", "Ask MR Agent"],
    )
    st.space("small")
    status_badge = ":green-badge[Validated]" if risk_run["validation_status"] == "VALIDATED" else ":red-badge[Rejected]"
    st.markdown(status_badge)
    st.caption(f"Data as of {current_risk['date']}")

if page == "Overview":
    st.title("Overview")
    st.caption("Management summary of the current validated demo risk run.")
    with st.container(horizontal=True):
        st.metric("Historical VaR (1 day, 99%)", amount(current_risk["var_hist"]), border=True)
        st.metric("Stressed VaR (SVaR)", amount(current_risk["stressed_var"]), border=True)
        st.metric("Expected shortfall (97.5%)", amount(current_risk["expected_shortfall"]), border=True)
        st.metric("Limit utilisation", percentage(current_risk["limit_utilisation"]), border=True)
    if alert_summary["action_required_count"]:
        st.warning(f"{alert_summary['action_required_count']} item(s) require review. See Alerts for detail.", icon=":material/warning:")
    else:
        st.success("No rule-based monitoring threshold is currently breached.", icon=":material/check_circle:")
    with st.container(border=True):
        st.subheader("Current run")
        st.write(f"**{lineage.get('run_id', 'Unavailable')}** · {lineage.get('source_file', 'Unavailable')}")
        st.caption("The displayed run ID is generated by the demo adapter when the source export contains no run ID.")

elif page == "VaR":
    st.title("VaR")
    st.caption("Historical VaR, stressed VaR, limit monitoring and current attribution.")
    with st.container(horizontal=True):
        st.metric("Historical VaR (1 day, 99%)", amount(current_risk["var_hist"]), percentage(trend["change_pct"]), border=True)
        st.metric("Stressed VaR (SVaR)", amount(current_risk["stressed_var"]), border=True)
        st.metric("Approved VaR limit", amount(limit["var_limit"]), border=True)
        st.metric("Limit utilisation", percentage(limit["utilisation_pct"]), border=True)
    with st.container(border=True):
        st.subheader("Historical VaR evolution")
        st.line_chart(df.set_index("cob_date")[["var_1d_99_hist"]].rename(columns={"var_1d_99_hist": "Historical VaR"}))
        st.caption(f"Latest movement: {amount(trend['change'])} ({percentage(trend['change_pct'])}) versus the prior observation.")
    with st.container(border=True):
        st.subheader("Historical VaR attribution")
        attribution = pd.Series(v8.get_var_attribution(), name="VaR contribution").sort_values(ascending=False)
        st.bar_chart(attribution)
        display_amount_table(attribution.rename_axis("Risk factor").reset_index(), ["VaR contribution"])
        st.caption("Contributions are displayed exactly as supplied by the risk-engine data.")

elif page == "P&L":
    st.title("P&L")
    st.caption("Current P&L, time series, explain drivers and backtesting results.")
    pnl = v8.get_pnl_analysis()
    with st.container(horizontal=True):
        st.metric("Actual P&L", amount(pnl["actual_pnl"]), border=True)
        st.metric("Hypothetical P&L", amount(pnl["hypothetical_pnl"]), border=True)
        st.metric("Clean P&L", amount(pnl["clean_pnl"]), border=True)
        st.metric("Unexplained P&L", amount(pnl["unexplained_pnl"]), border=True)
    with st.container(border=True):
        st.subheader("P&L evolution")
        pnl_history = df.set_index("cob_date")[["actual_pnl", "hypothetical_pnl", "clean_pnl", "unexplained_pnl"]]
        pnl_history.columns = ["Actual P&L", "Hypothetical P&L", "Clean P&L", "Unexplained P&L"]
        st.line_chart(pnl_history)
    with st.container(border=True):
        st.subheader("Current P&L explain drivers")
        driver_columns = [column for column in df.columns if column.startswith("pnl_driver_")]
        drivers = df.iloc[-1][driver_columns].rename(lambda column: column.replace("pnl_driver_", "").replace("_", " ").upper())
        st.bar_chart(drivers.sort_values())
        display_amount_table(drivers.rename_axis("Driver").rename("P&L impact").reset_index(), ["P&L impact"])
    with st.container(border=True):
        st.subheader("Backtesting")
        with st.container(horizontal=True):
            st.metric("250-day exceptions", backtesting["exception_count_250d"], border=True)
            st.metric("Hypothetical exception today", backtesting["hypothetical_exception"], border=True)
            st.metric("Actual exception today", backtesting["actual_exception"], border=True)
            st.metric("Traffic-light zone", backtesting["basel_traffic_light_zone"], border=True)

elif page == "Stress":
    st.title("Stress")
    st.caption("Current stress impacts and their evolution through the supplied risk-run observations.")
    st.info(stress_evolution["usage_note"], icon=":material/info:")
    latest_stress = stress_frame.iloc[-1].drop(labels="cob_date").sort_values()
    stress_table = pd.DataFrame({
        "Scenario": latest_stress.index,
        "Current P&L impact": latest_stress.values,
        "Source": [stress_metadata[name]["source"] for name in latest_stress.index],
        "Scenario theme": [stress_metadata[name]["theme"] for name in latest_stress.index],
    })
    with st.container(border=True):
        st.subheader("Current scenario impacts")
        display_amount_table(stress_table, ["Current P&L impact"])
    with st.container(border=True):
        st.subheader("Stress evolution by scenario")
        scenario_names = [column for column in stress_frame.columns if column != "cob_date"]
        selected_scenarios = st.multiselect(
            "Scenarios to display",
            scenario_names,
            default=scenario_names,
            help="Every selected scenario is shown as a separate curve.",
        )
        if selected_scenarios:
            st.line_chart(stress_frame.set_index("cob_date")[selected_scenarios])
        else:
            st.info("Select at least one scenario to display its evolution.", icon=":material/show_chart:")

elif page == "Controls & risk run":
    st.title("Controls & risk run")
    st.caption("Validation, lineage, data-quality checks and risk controls for the current run.")
    with st.container(horizontal=True):
        st.metric("Validation", risk_run["validation_status"], border=True)
        st.metric("Rows validated", lineage.get("row_count", 0), border=True)
        st.metric("Portfolios", lineage.get("portfolio_count", 0), border=True)
        st.metric("Duplicate dates", lineage.get("duplicate_date_count", 0), border=True)
    with st.container(border=True):
        st.subheader("Run lineage")
        lineage_table = pd.DataFrame([
            ("Run ID", lineage.get("run_id")), ("Source", lineage.get("source_type")),
            ("Source file", lineage.get("source_file")), ("Fingerprint", lineage.get("data_fingerprint")),
            ("As-of date", lineage.get("as_of_date")), ("Ingested at (UTC)", lineage.get("ingested_at_utc")),
        ], columns=["Field", "Value"])
        st.dataframe(lineage_table, hide_index=True)
        st.caption(lineage.get("run_id_note", ""))
        st.caption(lineage.get("approval_note", ""))
    with st.container(border=True):
        st.subheader("Data-quality checks")
        quality = pd.DataFrame([v8.validate_data()]).T.rename(columns={0: "Result"}).reset_index(names="Control")
        st.dataframe(quality, hide_index=True)
    if risk_run["errors"]:
        st.error("\n".join(risk_run["errors"]))
    if risk_run["warnings"]:
        st.warning("\n".join(risk_run["warnings"]))

elif page == "Alerts":
    st.title("Alerts")
    st.caption("Transparent rules for limit utilisation, VaR movement, backtesting, data quality and stress results.")
    for alert in alert_summary["alerts"]:
        with st.container(border=True):
            st.markdown(f"{alert_badge(alert['severity'])}  **{alert['title']}**")
            st.write(alert["summary"])

else:
    st.title("Ask MR Agent")
    st.caption("The agent investigates deterministic risk results, stress evolution and run lineage.")
    with st.container(border=True):
        selected_question = None
        if not st.session_state.risk_agent_messages:
            selected_question = st.pills(
                "Suggested questions",
                ["How has stress evolved across scenarios?", "What is the status and scope of this risk run?", "What are the main VaR and P&L risks today?"],
                label_visibility="collapsed",
            )
        for message in st.session_state.risk_agent_messages:
            avatar = ":material/analytics:" if message["role"] == "assistant" else None
            with st.chat_message(message["role"], avatar=avatar):
                st.markdown(message["content"])
        typed_question = st.chat_input("Ask about the current market-risk position", submit_mode="disable")
        question = typed_question or selected_question
        if question:
            st.session_state.risk_agent_messages.append({"role": "user", "content": question})
            with st.chat_message("user"):
                st.markdown(question)
            with st.chat_message("assistant", avatar=":material/analytics:"):
                with st.status("Running the risk investigation...", expanded=True) as status:
                    try:
                        answer = v13.ask_risk_agent(question)
                    except Exception as error:
                        status.update(label="Investigation could not be completed", state="error")
                        st.error(str(error), icon=":material/error:")
                    else:
                        status.update(label="Investigation complete", state="complete", expanded=False)
                        st.markdown(answer)
                        st.session_state.risk_agent_messages.append({"role": "assistant", "content": answer})
    with st.expander("Recent investigation memory", icon=":material/history:"):
        memory = v13.v9.get_recent_investigation_context()
        st.caption(memory["usage_note"])
        if memory["recent_investigations"]:
            for record in reversed(memory["recent_investigations"]):
                st.markdown(f"**{record['question']}**")
                st.caption(f"{record['timestamp_utc']} · tools: {', '.join(record['tools_used'])}")
        else:
            st.info("No completed investigations have been recorded for this data snapshot yet.", icon=":material/info:")
