"""V12 risk-run ingestion and validation for the Market Risk AI demo.

This module deliberately models a generic downstream interface.  It does not
represent any bank's internal architecture or data contract.
"""

from __future__ import annotations

import hashlib
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd


REQUIRED_COLUMNS = {
    "cob_date",
    "portfolio_id",
    "reporting_currency",
    "var_1d_99_hist",
    "stressed_var_1d_99",
    "expected_shortfall_97_5",
    "var_limit_amount",
    "var_limit_utilization_pct",
    "actual_pnl",
    "hypothetical_pnl",
    "backtest_exception_count_250d",
}

NUMERIC_COLUMNS = REQUIRED_COLUMNS - {
    "cob_date",
    "portfolio_id",
    "reporting_currency",
}


def _fingerprint(source_path: Path) -> str:
    """Return a short, content-based identifier for traceable demo runs."""
    return hashlib.sha256(source_path.read_bytes()).hexdigest()[:16]


def ingest_and_validate_risk_run(source_path: str | Path) -> dict:
    """Validate a risk-engine CSV and return curated data plus safe lineage.

    A real production adapter would receive an explicit run ID, source-system
    name, model version and approval status.  The existing demo CSV has none of
    these fields, so V12 generates only a deterministic *demo* run ID and calls
    the result ``VALIDATED`` rather than ``APPROVED``.
    """
    path = Path(source_path)
    if not path.exists():
        return {
            "validation_status": "REJECTED",
            "errors": [f"Risk-run file was not found: {path.name}"],
            "warnings": [],
            "data": pd.DataFrame(),
            "lineage": {"source_file": path.name},
        }

    try:
        raw_data = pd.read_csv(path)
    except (OSError, pd.errors.ParserError, UnicodeDecodeError) as error:
        return {
            "validation_status": "REJECTED",
            "errors": [f"Risk-run file could not be read: {error}"],
            "warnings": [],
            "data": pd.DataFrame(),
            "lineage": {"source_file": path.name},
        }

    errors = []
    warnings = []
    missing_columns = sorted(REQUIRED_COLUMNS - set(raw_data.columns))
    if missing_columns:
        errors.append("Missing required columns: " + ", ".join(missing_columns))

    data = raw_data.copy()
    if "cob_date" in data:
        data["cob_date"] = pd.to_datetime(data["cob_date"], errors="coerce")
        invalid_dates = int(data["cob_date"].isna().sum())
        if invalid_dates:
            errors.append(f"{invalid_dates} invalid or missing COB date(s).")
    else:
        invalid_dates = 0

    invalid_numeric_values = 0
    for column in NUMERIC_COLUMNS & set(data.columns):
        converted = pd.to_numeric(data[column], errors="coerce")
        invalid_numeric_values += int(converted.isna().sum() - data[column].isna().sum())
        data[column] = converted
    if invalid_numeric_values:
        errors.append(f"{invalid_numeric_values} invalid numeric value(s).")

    missing_values = int(data.isna().sum().sum())
    duplicate_dates = int(data["cob_date"].duplicated().sum()) if "cob_date" in data else 0
    if duplicate_dates:
        warnings.append(f"{duplicate_dates} duplicate COB date(s) retained for review.")
    if data.empty:
        errors.append("Risk run contains no data rows.")

    fingerprint = _fingerprint(path)
    latest_date = None
    earliest_date = None
    if "cob_date" in data and data["cob_date"].notna().any():
        earliest_date = str(data["cob_date"].min().date())
        latest_date = str(data["cob_date"].max().date())

    validation_status = "VALIDATED" if not errors else "REJECTED"
    lineage = {
        "run_id": f"DEMO-RUN-{latest_date or 'UNKNOWN'}-{fingerprint[:8]}",
        "run_id_note": "Generated by the V12 demo adapter because the source CSV has no supplied run ID.",
        "source_file": path.name,
        "source_type": "CSV risk-engine export",
        "data_fingerprint": fingerprint,
        "ingested_at_utc": datetime.now(timezone.utc).isoformat(),
        "validation_status": validation_status,
        "approval_note": "Validation is a demo control and does not represent business approval.",
        "as_of_date": latest_date,
        "first_observation_date": earliest_date,
        "portfolio_count": int(data["portfolio_id"].nunique()) if "portfolio_id" in data else 0,
        "reporting_currencies": sorted(data["reporting_currency"].dropna().astype(str).unique().tolist())
        if "reporting_currency" in data
        else [],
        "row_count": int(len(data)),
        "column_count": int(len(data.columns)),
        "missing_value_count": missing_values,
        "duplicate_date_count": duplicate_dates,
        "invalid_date_count": invalid_dates,
    }
    return {
        "validation_status": validation_status,
        "errors": errors,
        "warnings": warnings,
        "data": data.sort_values("cob_date").reset_index(drop=True) if "cob_date" in data else data,
        "lineage": lineage,
    }
